CONVICTION_BULLET_ID = 0
CONVICTION_ID = 1
BUFF_ID = 2
HEAL_ID = 3
PLANE_LEVEL1_ID = 4
BOSS_STAGE1_ID = 5
BOSS_STAGE2_ID = 6
NORMAL_BULLET_ID = 7
SPECIAL_BULLET_ID = 8
PLANE_ICE_ID = 9


INF = 10000000

data = {
    CONVICTION_BULLET_ID : {
        'PATH' : '../pic/Bullet/ConvictionBullet.png',
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0.0,
        'POS_CD' : 0.02,
        'DIRECTION' : False,
        'LEFT' : False,
        'LEFT_PATH' : None,
        'RIGHT' : False,
        'RIGHT_PATH' : None,
        'SUMMON_CD': INF,
        'REVIVE' : False,
        'REVIVE_PATH' : None,
        'REVIVE_INDEX_MAX' : 0,
        'DIE' : False,
        'DIE_PATH' : None,
        'DIE_INDEX_MAX' : 0,
        'HP_BAR_INDEX' : 0,
        'SIZE' : (25, 25),
        'SPEED' : (25, 0),
        'HP' : INF,
        'TEARS' : None,
        'DAMAGE' : 1,
    },

    CONVICTION_ID : {
        'PATH' : '../pic/Staff/%d.png',
        'IMAGE_INDEX_MAX' : 43,
        'IMAGE_INDEX_CD' : 0.0,
        'POS_CD' : 0.08,
        'DIRECTION' : False,
        'LEFT' : False,
        'LEFT_PATH' : None,
        'RIGHT' : False,
        'RIGHT_PATH' : None,
        'SUMMON_CD': 0.02,
        'REVIVE' : False,
        'REVIVE_PATH' : None,
        'REVIVE_INDEX_MAX' : 0,
        'DIE' : False,
        'DIE_PATH' : None,
        'DIE_INDEX_MAX' : 0,
        'HP_BAR_INDEX' : 1,
        'SIZE' : (160, 120),
        'SPEED' : (1, 1),
        'HP' : 100,
        'TEARS' : 0.4,
        'DAMAGE' : 1,
    },

    BUFF_ID : {
        'PATH': '../pic/Buff/buff.png',
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0.0,
        'POS_CD' : 0.05,
        'DIRECTION' : False,
        'LEFT' : False,
        'LEFT_PATH' : None,
        'RIGHT' : False,
        'RIGHT_PATH' : None,
        'SUMMON_CD' : INF,
        'REVIVE' : False,
        'REVIVE_PATH' : None,
        'REVIVE_INDEX_MAX' : 0,
        'DIE' : False,
        'DIE_PATH' : None,
        'DIE_INDEX_MAX' : 0,
        'HP_BAR_INDEX' : 0,
        'SIZE' : (100, 100),
        'SPEED' : (-2.5, 0),
        'HP' : INF,
        'TEARS' : None,
        'DAMAGE' : None,
    },

    HEAL_ID: {
        'PATH': '../pic/Heal/heal.png',
        'IMAGE_INDEX_MAX': 0,
        'IMAGE_INDEX_CD': 0.0,
        'POS_CD': 0.05,
        'DIRECTION': False,
        'LEFT': False,
        'LEFT_PATH': None,
        'RIGHT': False,
        'RIGHT_PATH': None,
        'SUMMON_CD': INF,
        'REVIVE': False,
        'REVIVE_PATH': None,
        'REVIVE_INDEX_MAX': 0,
        'DIE': False,
        'DIE_PATH': None,
        'DIE_INDEX_MAX': 0,
        'HP_BAR_INDEX': 0,
        'SIZE': (100, 100),
        'SPEED': (-2.5, 0),
        'HP': INF,
        'TEARS': None,
        'DAMAGE': None,
    },

    PLANE_LEVEL1_ID : {
        'PATH' : '../pic/Plane_level1/move/%d.png',
        'IMAGE_INDEX_MAX' : 20,
        'IMAGE_INDEX_CD' : 0.08,
        'POS_CD' : 0.2,
        'DIRECTION' : False,
        'LEFT' : False,
        'LEFT_PATH' : None,
        'RIGHT' : False,
        'RIGHT_PATH' : None,
        'SUMMON_CD': 1,
        'REVIVE' : False,
        'REVIVE_PATH' : None,
        'REVIVE_INDEX_MAX' : 0,
        'DIE' : False,
        'DIE_PATH' : '../pic/Plane_level1/die/%d.png',
        'DIE_INDEX_MAX' : 10,
        'HP_BAR_INDEX' : 5,
        'SIZE' : (100, 50),
        'SPEED' :  (-5, 0),
        'HP' : 20,
        'TEARS' : 1,
        'DAMAGE' : 1,
    },

    BOSS_STAGE1_ID : {
        'PATH' : '../pic/Boss/Stage1_Move/Left/%d.png',
        'IMAGE_INDEX_MAX' : 18,
        'IMAGE_INDEX_CD' : 0.08,
        'POS_CD' : 0.2,
        'DIRECTION' : True,
        'LEFT' : True,
        'LEFT_PATH' : '../pic/Boss/Stage1_Move/Left/%d.png',
        'RIGHT' : False,
        'RIGHT_PATH' : '../pic/Boss/Stage1_Move/Right/%d.png',
        'SUMMON_CD': 1,
        'REVIVE' : False,
        'REVIVE_PATH' : '../pic/Boss/Stage1_Revive/%d.png',
        'REVIVE_INDEX_MAX' : 21,
        'DIE' : False,
        'DIE_PATH' : None,
        'DIE_INDEX_MAX' : 0,
        'HP_BAR_INDEX' : 0.2,
        'SIZE' : (150, 150),
        'SPEED' :  (15, 15),
        'HP' : 500,
        'TEARS' : 1,
        'DAMAGE' : 1,
    },

    BOSS_STAGE2_ID: {
        'PATH': '../pic/Boss/Stage2_Move/Left/%d.png',
        'IMAGE_INDEX_MAX': 14,
        'IMAGE_INDEX_CD': 0.08,
        'POS_CD': 0.05,
        'DIRECTION': True,
        'LEFT': True,
        'LEFT_PATH': '../pic/Boss/Stage2_Move/Left/%d.png',
        'RIGHT': False,
        'RIGHT_PATH': '../pic/Boss/Stage2_Move/Right/%d.png',
        'SUMMON_CD': 1,
        'REVIVE': False,
        'REVIVE_PATH': None,
        'REVIVE_INDEX_MAX': 0,
        'DIE' : False,
        'DIE_PATH' : '../pic/Boss/Stage2_Die/Left/%d.png',
        'DIE_INDEX_MAX' : 33,
        'HP_BAR_INDEX' : 0.5,
        'SIZE' : (50, 50),
        'SPEED' : (25, 25),
        'HP' : 100,
        'TEARS' : None,
        'DAMAGE' : 1,
    },

    NORMAL_BULLET_ID: {
        'PATH' : '../pic/Bullet/NormalBullet.png',
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0.0,
        'POS_CD' : 0.01,
        'DIRECTION' : False,
        'LEFT' : False,
        'LEFT_PATH' : None,
        'RIGHT' : False,
        'RIGHT_PATH' : None,
        'SUMMON_CD': INF,
        'REVIVE' : False,
        'REVIVE_PATH' : None,
        'REVIVE_INDEX_MAX' : 0,
        'DIE' : False,
        'DIE_PATH' : None,
        'DIE_INDEX_MAX' : 0,
        'HP_BAR_INDEX' : 0,
        'SIZE' : (25, 25),
        'SPEED' : (5, 5),
        'HP' : INF,
        'TEARS' : None,
        'DAMAGE' : 1,
    },

    SPECIAL_BULLET_ID: {
        'PATH' : '../pic/Bullet/SpecialBullet.png',
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0.0,
        'POS_CD' : 0.01,
        'DIRECTION' : False,
        'LEFT' : False,
        'LEFT_PATH' : None,
        'RIGHT' : False,
        'RIGHT_PATH' : None,
        'SUMMON_CD': INF,
        'REVIVE' : False,
        'REVIVE_PATH' : None,
        'REVIVE_INDEX_MAX' : 0,
        'DIE' : False,
        'DIE_PATH' : None,
        'DIE_INDEX_MAX' : 0,
        'HP_BAR_INDEX' : 0,
        'SIZE' : (25, 25),
        'SPEED' : (5, 5),
        'HP' : INF,
        'TEARS' : None,
        'DAMAGE' : 5,
    },

    PLANE_ICE_ID: {
        'PATH': '../pic/Plane_Ice/move/%d.png',
        'IMAGE_INDEX_MAX': 12,
        'IMAGE_INDEX_CD': 0.08,
        'POS_CD': 0.2,
        'DIRECTION': False,
        'LEFT': False,
        'LEFT_PATH': None,
        'RIGHT': False,
        'RIGHT_PATH': None,
        'SUMMON_CD': 1,
        'REVIVE': False,
        'REVIVE_PATH': None,
        'REVIVE_INDEX_MAX': 0,
        'DIE': False,
        'DIE_PATH': '../pic/Plane_Ice/die/%d.png',
        'DIE_INDEX_MAX': 10,
        'HP_BAR_INDEX': 5,
        'SIZE': (100, 50),
        'SPEED': (-5, 0),
        'HP': 20,
        'TEARS': None,
        'DAMAGE': 1,
    },

}